[package]
name = "vm"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]

[dependencies.linked-stack]
path = "../linked-stack"

[dependencies.serde]
version = "1.*.*"
features = ["rc"]

[dependencies]
serde_derive = "1.*.*"

[dependencies.rpds]
version  = "0.3.0"
features = ["serde"]
