[package]
name = "emit"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]

[dependencies]
typed-arena = "1.3.0"

[dependencies.binder]
path = "../binder"

[dependencies.lexer]
path = "../lexer"

[dependencies.parser]
path = "../parser"

[dependencies.vm]
path = "../vm"
