language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
script:
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cargo build --verbose;
      cargo test --verbose;
      cargo bench --verbose;
    else
      cargo build --verbose;
      cargo test --verbose;
    fi
notifications:
  email: false
